### PR TITLE
Deletion of project in project tree and windows compatible imports added

### PR DESCRIPTION
**Pull request by odddkidout**
added deletion feature 
Import modules fixed for windows. by fixing the system variable.

### CODE REVIEW

**Comment by genedan** [comment]
Thanks! I'll take a look at this. Now that we've begun to have multiple contributors, I think we ought to make a testing suite so that we can run pytest before merging in any pull requests - that way we can make sure all the features work as intended.

One thing I did notice upon quick glance was the removal of the faslr. prefixes in the module imports. Do you have any trouble with the imports with that prefix in there? Having the prefix will be important to avoid naming clashes (for example, if there is another package called "constants" in sys.path, importing the module with faslr.constants helps avoid the conflict).

What is your IDE setup like? In my PyCharm IDE, I have the FASLR/faslr directory marked as the Namespace Package - so I actually get errors on my end if I do not include the prefix.

I'll start work on a contributing guide to establish the conventions that we ought to follow.

**Comment by odddkidout** [comment]
yeah, i was having import errors with faslr prefix so i removed it and added root path to system path variable.
i use vs code as IDE. having a document for convention and roadmap will help us a lot to get more productive.

can we make a discord server for the discussion and planning?
it will help us to collaborate better :)

**Comment by genedan** [comment]
I think discord will be too much for me to manage personally - I already have enough social media overload so it would be hard for me to organize things if we added another platform. GitHub has a bunch of project management tools I think we should make use of and keeping all dev discussions in one place will make it easier for the public to see how this project was made in its entirety.

It would be fine if you or other people made their own independent discord if they wanted to talk about the project informally, but I'll be conducting the formal workflow stuff from GitHub.

**Comment by genedan** [comment]
Thanks again for the new method. I made some edits - notably that when a project is deleted, we want the children to be deleted but not the parents. For example if you are reserving for multiple states within a country, you wouldn't want all the states to be deleted along with the country.

**Pull request merged**
