### PR TITLE
heatmap improved

### PR DESCRIPTION
**Pull request by odddkidout**
Hi @genedan ,

I have made a custom function for parsing CSS without any external dependencies. The runtime has improved significantly.

Old code benchmarks:

Elapsed time: 0.5885899066925049 seconds
Elapsed time: 0.045998573303222656 seconds
Elapsed time: 0.04100298881530762 seconds
Elapsed time: 0.04895329475402832 seconds
Elapsed time: 0.043003082275390625 seconds

Improved code benchmarks

Elapsed time: 0.268422 seconds
Elapsed time: 0.029973 seconds
Elapsed time: 0.032594 seconds
Elapsed time: 0.013456 seconds
Elapsed time: 0.037533 seconds

### CODE REVIEW

**Comment by odddkidout** [comment]
Hi @genedan ,

I have updated code and the new benchmarks for the code.

Elapsed time: 0.295686 seconds
Elapsed time: 0.028154 seconds
Elapsed time: 0.028240 seconds
Elapsed time: 0.014430 seconds
Elapsed time: 0.034262 seconds
Elapsed time: 0.017297 seconds

seems like it's reduced to 60-70% of the runtime

**Comment by odddkidout** [comment]
Also for the designing of unit tests, I think i need to go through the reserving method from Friedland.

At this moment I don't have expertise in the same. if you can guide me. i would like to write tests and understand the workings 
at a deeper level

**Comment by genedan** [comment]
I went ahead and wrote a unit test here:

https://github.com/casact/FASLR/blob/main/faslr/tests/utilities/test_style_parser.py

What it does is it loads a sample triangle and then runs parse_styler on it. It also loads a preset data frame of the correct colors and then compares that with the output of the function. If they are the same, the test passes.

You can run pytest against the tests folder to see if your code works. I'm only 15/250 pages into a pytest book myself, so it will take me some time as well to learn the library. Eventually we'll be able to run all the tests automatically for each pull request via GitHub actions.

**Comment by odddkidout** [comment]
Thanks for the help.

I have run the test, and it's passing. 

I think its better to make CI/CD pipelines with codecov to keep a track of code coverage tested.

**Comment by genedan** [comment]
I'm reviewing this now. You should see some commits coming in from my end adding some annotations.

**Pull request merged**
